/**
 * Markdown formatters for GitLab milestone and issue descriptions.
 *
 * All functions produce GitLab-flavored markdown strings ready
 * for the `description` field of the GitLab API.
 */

// ─── Milestone ───────────────────────────────────────────────────────────────

export interface MilestoneData {
  id: string;
  title: string;
  vision?: string;
  successCriteria?: string[];
  slices?: Array<{ id: string; title: string; taskCount?: number }>;
}

/**
 * Format a GitLab milestone description body.
 */
export function formatMilestoneBody(data: MilestoneData): string {
  const lines: string[] = [];

  lines.push(`# ${data.id}: ${data.title}`);
  lines.push("");

  if (data.vision) {
    lines.push("## Vision");
    lines.push(data.vision);
    lines.push("");
  }

  if (data.successCriteria?.length) {
    lines.push("## Success Criteria");
    for (const criterion of data.successCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  if (data.slices?.length) {
    lines.push("## Slices");
    lines.push("");
    lines.push("| Slice | Title | Tasks |");
    lines.push("|-------|-------|-------|");
    for (const slice of data.slices) {
      lines.push(`| \`${slice.id}\` | ${slice.title} | ${slice.taskCount ?? "—"} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Auto-generated by GSD GitLab Sync*");

  return lines.join("\n");
}

// ─── Issue ──────────────────────────────────────────────────────────────────

export interface IssueData {
  id: string;
  title?: string;
  description?: string;
  labels?: string[];
  files?: string[];
  verifyCriteria?: string[];
  sliceId?: string;
  sliceTitle?: string;
}

/**
 * Format a GitLab issue description body.
 */
export function formatIssueBody(data: IssueData): string {
  const lines: string[] = [];

  lines.push(`## ${data.id}: ${data.title ?? data.id}`);
  lines.push("");

  if (data.sliceId && data.sliceTitle) {
    lines.push(`**Slice:** ${data.sliceId} — ${data.sliceTitle}`);
    lines.push("");
  }

  if (data.description) {
    lines.push(data.description);
    lines.push("");
  }

  if (data.files?.length) {
    lines.push("### Files");
    for (const file of data.files) {
      lines.push(`- \`${file}\``);
    }
    lines.push("");
  }

  if (data.verifyCriteria?.length) {
    lines.push("### Verification");
    for (const criterion of data.verifyCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Summary ────────────────────────────────────────────────────────────────

export interface SummaryData {
  oneLiner?: string;
  body?: string;
  frontmatter?: Record<string, unknown>;
}

/**
 * Format a summary comment (e.g. for issue close notes).
 */
export function formatSummaryComment(data: SummaryData): string {
  const lines: string[] = [];

  if (data.oneLiner) {
    lines.push(`**Summary:** ${data.oneLiner}`);
    lines.push("");
  }

  if (data.body) {
    lines.push(data.body);
    lines.push("");
  }

  if (data.frontmatter && Object.keys(data.frontmatter).length > 0) {
    lines.push("<details>");
    lines.push("<summary>Metadata</summary>");
    lines.push("");
    lines.push("```yaml");
    for (const [key, value] of Object.entries(data.frontmatter)) {
      lines.push(`${key}: ${JSON.stringify(value)}`);
    }
    lines.push("```");
    lines.push("");
    lines.push("</details>");
  }

  return lines.join("\n");
}

// ─── Merge Request ───────────────────────────────────────────────────────────

export interface MRData {
  id: string;
  sliceId: string;
  sliceTitle: string;
  milestoneId: string;
  milestoneTitle: string;
  vision?: string;
  slices?: Array<{ id: string; title: string; taskCount?: number }>;
  taskCount?: number;
  verifyCriteria?: string[];
}

/**
 * Format a GitLab MR description body for a slice.
 */
export function formatMRBody(data: MRData): string {
  const lines: string[] = [];

  lines.push(`## ${data.sliceId}: ${data.sliceTitle}`);
  lines.push("");
  lines.push(`**Milestone:** ${data.milestoneId} — ${data.milestoneTitle}`);
  lines.push("");

  if (data.vision) {
    lines.push("### Vision");
    lines.push(data.vision);
    lines.push("");
  }

  if (data.taskCount !== undefined) {
    lines.push(`**Tasks completed:** ${data.taskCount}`);
    lines.push("");
  }

  if (data.verifyCriteria?.length) {
    lines.push("### Verification");
    for (const criterion of data.verifyCriteria) {
      lines.push(`- [ ] ${criterion}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Auto-generated by GSD GitLab Sync*");

  return lines.join("\n");
}

// ─── Task Close Note ────────────────────────────────────────────────────────

export interface TaskCloseNoteData {
  taskId: string;
  oneLiner?: string;
  narrative?: string;
  keyFiles?: string[];
  keyDecisions?: string[];
  verification?: string;
  commitSha?: string;
}

/**
 * Format a task completion note to post as an issue comment.
 * Used when a task is marked complete — posts the summary to the
 * parent slice issue or dedicated task issue in GitLab.
 */
export function formatTaskCloseNote(data: TaskCloseNoteData): string {
  const lines: string[] = [];

  lines.push(`### ✅ Task ${data.taskId} Complete`);
  lines.push("");

  if (data.oneLiner) {
    lines.push(`**${data.oneLiner}**`);
    lines.push("");
  }

  if (data.narrative) {
    lines.push(data.narrative);
    lines.push("");
  }

  if (data.verification) {
    lines.push("**Verification:**");
    lines.push(data.verification);
    lines.push("");
  }

  if (data.keyFiles?.length) {
    lines.push("**Key files:**");
    for (const file of data.keyFiles) {
      lines.push(`- \`${file}\``);
    }
    lines.push("");
  }

  if (data.keyDecisions?.length) {
    lines.push("**Key decisions:**");
    for (const decision of data.keyDecisions) {
      lines.push(`- ${decision}`);
    }
    lines.push("");
  }

  if (data.commitSha) {
    lines.push(`_Commit: \`${data.commitSha.substring(0, 8)}\`_`);
    lines.push("");
  }

  return lines.join("\n");
}
