import { describe, it } from "node:test";
import assert from "node:assert/strict";
import {
  formatMilestoneBody,
  formatIssueBody,
  formatSummaryComment,
} from "../templates.ts";

describe("gitlab-sync templates", () => {
  describe("formatMilestoneBody", () => {
    it("includes id and title", () => {
      const body = formatMilestoneBody({
        id: "M001",
        title: "Build Auth",
        vision: "Secure authentication for all users",
      });
      assert.ok(body.includes("M001: Build Auth"));
      assert.ok(body.includes("Secure authentication"));
    });

    it("renders success criteria as checkboxes", () => {
      const body = formatMilestoneBody({
        id: "M001",
        title: "Auth",
        successCriteria: ["Users can log in", "OAuth works"],
      });
      assert.ok(body.includes("- [ ] Users can log in"));
      assert.ok(body.includes("- [ ] OAuth works"));
    });

    it("renders slice table", () => {
      const body = formatMilestoneBody({
        id: "M001",
        title: "Auth",
        slices: [
          { id: "S01", title: "Core types", taskCount: 3 },
          { id: "S02", title: "OAuth", taskCount: 5 },
        ],
      });
      // IDs are backtick-escaped in markdown table cells
      assert.ok(body.includes("| `S01` | Core types | 3 |"));
      assert.ok(body.includes("| `S02` | OAuth | 5 |"));
    });

    it("includes auto-generated footer", () => {
      const body = formatMilestoneBody({ id: "M001", title: "Test" });
      assert.ok(body.includes("*Auto-generated by GSD GitLab Sync*"));
    });
  });

  describe("formatIssueBody", () => {
    it("includes title and description", () => {
      const body = formatIssueBody({
        id: "T01",
        title: "Add auth types",
        description: "Define all auth-related types",
        files: ["src/auth/types.ts"],
        verifyCriteria: ["Types compile"],
      });
      assert.ok(body.includes("T01: Add auth types"));
      assert.ok(body.includes("Define all auth-related types"));
    });

    it("includes slice metadata when provided", () => {
      const body = formatIssueBody({
        id: "T01",
        title: "Add types",
        sliceId: "S01",
        sliceTitle: "Core Auth",
      });
      assert.ok(body.includes("**Slice:** S01 — Core Auth"));
    });

    it("renders file list as code", () => {
      const body = formatIssueBody({
        id: "T01",
        title: "Add types",
        files: ["src/types.ts", "src/utils.ts"],
      });
      assert.ok(body.includes("`src/types.ts`"));
      assert.ok(body.includes("`src/utils.ts`"));
    });

    it("renders verification criteria as checkboxes", () => {
      const body = formatIssueBody({
        id: "T01",
        title: "Add types",
        verifyCriteria: ["Types compile", "Tests pass"],
      });
      assert.ok(body.includes("- [ ] Types compile"));
      assert.ok(body.includes("- [ ] Tests pass"));
    });

    it("omits empty optional sections", () => {
      const body = formatIssueBody({ id: "T01", title: "Minimal task" });
      assert.ok(!body.includes("### Files"));
      assert.ok(!body.includes("### Verification"));
      assert.ok(!body.includes("**Slice:**"));
    });
  });

  describe("formatSummaryComment", () => {
    it("includes one-liner and body", () => {
      const comment = formatSummaryComment({
        oneLiner: "Added retry logic",
        body: "Implemented exponential backoff",
      });
      assert.ok(comment.includes("**Summary:** Added retry logic"));
      assert.ok(comment.includes("Implemented exponential backoff"));
    });

    it("wraps frontmatter in details block", () => {
      const comment = formatSummaryComment({
        frontmatter: { duration: "45m", key_files: ["a.ts"] },
      });
      assert.ok(comment.includes("<details>"));
      assert.ok(comment.includes("duration:"));
    });

    it("empty input produces empty string — callers gate on truthiness", () => {
      const comment = formatSummaryComment({});
      assert.equal(comment, "", "empty data must return exactly ''");
      assert.doesNotMatch(comment, /undefined|null|\[object Object\]/);
    });
  });
});
